# Generated by Django 4.1.5 on 2023-01-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="case",
            field=models.ManyToManyField(to="case.case"),
        ),
        migrations.AlterField(
            model_name="person",
            name="birthdate",
            field=models.DateField(),
        ),
    ]
