# Generated by Django 4.1.5 on 2023-01-27 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_database_device_geodata_database_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodata',
            name='type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='database',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case.database'),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
