FROM python:3.10

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN pip install --upgrade pip
COPY ../../requirements.txt /usr/src/app
RUN \
  apt-get update && \
  apt-get install -y spatialite-bin libsqlite3-mod-spatialite \
     binutils libproj-dev gdal-bin && \
  pip install -U pip && pip install pipenv && \
  rm -rf /var/lib/apt/lists/*
RUN pip install -r requirements.txt

# copy project
COPY ../.. /usr/src/app